### ISSUE TITLE
Get Landscape SaaS button is broken

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/landscape-brochure.internal#12]
From try-landscape, click the green button saying 'Get Landscape SaaS'

Be sad when you see 404 http://landscape-brochure.wherever/signup

**Comment by nottrobin** [comment]
@sparkiegeek since https://landscape.canonical.com/signup requires SSO login, would it be possible to handle this your side, at least for now?

I'm not sure whether this page feels more like part of the app or part of the public site, but it would certainly be much more complex to implement than anything our application handles so far. If we could keep it your side for now, that would be very helpful for us to be able to get this live, and then we can discuss whether we take it over down the line. Would that be possible?
